#!/usr/bin/env python
# author: N037 D4w3

import argparse

parser = argparse.ArgumentParser()
parser.add_argument('-u', '--user', required=True,
        help="CERN username")
parser.add_argument('packages_file',
        default='packages.txt',
        nargs='?',
        help='package listing '
             '(default: packages.txt)')
args = parser.parse_args()

import os
import sys
import subprocess
import shutil
from toolman import packages


USER = args.user
SVNBASE = packages.SVNBASE.format(**locals())


for package in packages.read_packages(args.packages_file):
    url = os.path.join(SVNBASE, package.path)
    outpath = os.path.join(packages.BASE, package.name)
    # update
    if os.path.exists(outpath):
        print "updating %s..." % package.name
        print "This will remove and recreate %s" % outpath
        if raw_input("Continue? (Y/[n]) ") == 'Y':
            shutil.rmtree(outpath)
        else:
            continue
    # checkout
    print "checking out %s (%s)..." % (package.name, package.path)
    if subprocess.call(['svn', 'co', url, outpath]):
        print "failed to checkout %s!" % package.name
