#!/bin/bash

if [ -d packages/JetUncertainties ]
then
    echo "patching JetUncertainties..."
    if [ ! -d packages/JetUncertainties/share/analysisPlots ]
    then
        cp -r packages/JetUncertainties/analysisPlots packages/JetUncertainties/share/analysisPlots
    fi
    cp patches/JetUncertainties/*.config packages/JetUncertainties/share/
fi
if [ -d packages/MissingETUtility ]
then
    echo "patching MissingETUtility..."
    cp patches/MissingETUtility/LinkDef.h packages/MissingETUtility/Root/LinkDef.h
fi
echo "done"
