#!/bin/bash

if [ -d src/common/TauTriggerEmulation ]
then
    echo "patching TauTriggerEmulation ..."
    share=src/common/TauTriggerEmulation/share
    cp patches/TauTriggerEmulation/config_EF_DiTau.xml $share
    cp patches/TauTriggerEmulation/config_EF_DiTau_with_resurrected.xml $share

    cp patches/TauTriggerEmulation/EF_tau29_medium1_tau20_medium1_Hypo_00_02_35.xml $share/triggers/TrigTauHypo_00_02_35/
    cp patches/TauTriggerEmulation/EF_tau29_medium1_tau20_medium1_Hypo_00_02_42.xml $share/triggers/TrigTauHypo_00_02_42/
    cp patches/TauTriggerEmulation/EF_tau29_medium1_tau20_medium1_Hypo_00_03_02.xml $share/triggers/TrigTauHypo_00_03_02/
    cp patches/TauTriggerEmulation/EF_tau29T_medium1_tau20T_medium1_Hypo_00_03_02.xml $share/triggers/TrigTauHypo_00_03_02/
fi

if [ -d src/bundle_2011/TauTriggerCorrections ]
then
    echo "patching TauTriggerCorrections ..."
    if [ -d src/bundle_2011/TauTriggerCorrections/root ]
    then
        mv src/bundle_2011/TauTriggerCorrections/root src/bundle_2011/TauTriggerCorrections/share
    fi
fi

if [ -d src/bundle_2012/TauFakeRates ]
then
    echo "patching TauFakeRates ..."
    sed -i 's/TRoot/TROOT/g' src/bundle_2012/TauFakeRates/Root/Helper.cxx
fi

if [ -d src/bundle_2012/TrigMuonEfficiency ]
then
    echo "patching TrigMuonEfficiency ..."
	cp patches/bundle_2012/TrigMuonEfficiency/* src/bundle_2012/TrigMuonEfficiency/share/.
fi

if [ -d src/common/MuonEfficiencyCorrections ]
then
    echo "patching MuonEfficiencyCorrections ..."
    cp patches/MuonEfficiencyCorrections/LinkDef.h src/common/MuonEfficiencyCorrections/Root/.
fi

if [ -d src/common/MissingETUtility ]
then
    echo "patching MissingETUtility ..."
    cp patches/MissingETUtility/LinkDef.h src/common/MissingETUtility/Root/.
fi
